name: Workflow Lint
on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
  schedule:
    # Noon (EST) once every Monday
    - cron: '0 4 * * 1'

jobs:
  lint:
    timeout-minutes: 2
    runs-on: Linux
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Lint
        uses: Brightspace/d2l-github-workflow-lint@master
